on:
  push:
    branches:
    - main
  
name: Build client

jobs:
  build-client:
    name: Build client
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download VB6 prefix
      run: |
        mkdir ".\vb6"
        Invoke-WebRequest -Uri "${{ secrets.VB6_URL }}" -OutFile ".\vb6\vb6.zip"
        Expand-Archive -Path ".\vb6\vb6.zip" -DestinationPath ".\vb6"
        reg import ".\vb6\vb6.reg"
        Start-Process -FilePath ".\vb6\vb6runplus.exe" -ArgumentList "/silent" -Wait -PassThru
    - name: Build client
      run: |
        mkdir ".\dist"
        Start-Process -FilePath ".\vb6\vb6.exe" -ArgumentList "/make",".\client\Project1.vbp","/outdir",".\dist\" -Wait -PassThru
        ..\client\mkdirs.bat
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: client
        path: dist/
        if-no-files-found: error
