on:
  push:
    branches:
      - main
    tags-ignore:
      - latest
      - main

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

name: Release

permissions:
  contents: write

jobs:
  client:
    uses: ./.github/workflows/client.yml
    secrets: inherit
  deploy:
    #needs: [client]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./.github/build-server.sh

    - uses: cardinalby/git-get-release-action@v1
      name: Get latest tagged release
      id: tagged_release
      with:
        latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: cardinalby/git-get-release-action@v1
      name: Get latest mainline release
      id: mainline_release
      with:
        tag: latest
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Print some debug stuff
      run: |
        set -x
        echo "${{ steps.mainline_release.outputs.assets[0].updated_at }}"
        echo "${{ steps.mainline_release.outputs.assets[0] }}"
        echo "${{ steps.mainline_release.outputs.assets }}"
        echo "${{ steps.mainline_release.outputs.created_at }}"
        echo "${{ steps.mainline_release.outputs.published_at }}"
        echo "${{ steps.mainline_release.outputs }}"
        echo "${{ steps.mainline_release.outputs }}"
        echo "${{ steps.mainline_release.outputs }}"
        echo "${{ steps.tagged_release.outputs }}"

    - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      name: Deploy website with FTPS
      with:
        server: arcticfox.doridian.net
        username: dsonline
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./server/
        server-dir: /public_html/
        security: strict
        protocol: ftps
        port: 21
        exclude: |
            **/.git*
            **/.git*/**
            **/config.php
