on:
  push:
    branches-ignore:
      - main
  workflow_call: {}

concurrency:
  group: server-${{ github.ref }}
  cancel-in-progress: true

name: Deploy website

permissions:
  contents: read

jobs:
  server:
    name: Build website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: ./.github/build-server.sh
