on:
  push: {}

name: Deploy website

jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git rev-parse HEAD > server/api/gitrev.txt
    - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      if: github.ref == 'refs/heads/main'
      with:
        server: arcticfox.doridian.net
        username: dsonline
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./server/
        server-dir: /public_html/
        security: strict
        protocol: ftps
        port: 21
        exclude: |
            **/.git*
            **/.git*/**
            **/mysql_config.php
